### ISSUE TITLE
分布式扩展

### ISSUE THREAD

**Issue by xzy666** [owenliang/go-id-alloc#2]
你好，有个问题请教一下
···
分布式：横向扩展，理论无上限
···
这个分布式扩展如何实现？ 我大概想了下 好像没有办法控制  在更新max_id的时候做分布式事务吗？

**Comment by owenliang** [comment]
@xzy666    加机器就可以了，重点在MYSQL事务，update会默认行锁，多节点请求max_id是悲观锁的。
